---
title: "Analysis"
output: 
  pdf_document: 
    fig_caption: yes
    latex_engine: xelatex
    number_sections: yes
    toc: no
---

```{r setup, include=FALSE, echo=FALSE, cache=FALSE}
knitr::opts_chunk$set(warning = TRUE, message = TRUE)
#require(knitr)
#knitr::opts_knit$set(root.dir = "~/devel/luftdaten-r/")
source('~/devel/luftdaten-r/evaluation/scripts/load.R', chdir=TRUE, local=TRUE)
#source("evaluation/scripts/func.R", chdir=TRUE, local=TRUE)
```

## Vergleich von Dortmund und Essen
Während die Anzahl von Sensoren in Dortmund `r length(do_sensors)` betragen, sind es in Essen `r length(e_sensors)`.

```{r sensor_maps_do, echo=FALSE, results='hide', fig.cap="Alle Sensoren im Stadtraum Dortmund", fig.width=3}
do_polygon_osm <- getTiles(x = do_polygon, type = "osm", crop = FALSE, zoom = 11, verbose = TRUE)

tm_shape(do_polygon_osm)+
  tm_rgb()+
  tm_shape(do_polygon)+
  tm_polygons(alpha=0.3, col="yellow")+
  qtm(do_sensors, symbols.col = "red", symbols.size = 0.4, symbols.alpha=0.5)
```
```{r sensor_maps_e, echo=FALSE, results='hide', fig.cap="Alle Sensoren im Stadtraum Essen", fig.width=3}
e_polygon_osm <- getTiles(x = e_polygon, type = "osm", crop=TRUE)
tm_shape(e_polygon_osm) + tm_rgb()+
  tm_shape(e_polygon) + tm_polygons(alpha=0.3, col="blue")+
qtm(e_sensors, symbols.col = "red", symbols.size = 0.4, symbols.alpha=0.5)
```
